batch_size: 256
data:
    dataset: cifar10
    dataset_path: ./data/cifar10/grayscale/
    model_to_prune_path: ./src/data/optimal_weights.npy
    layout_path: ./src/data/layout.csv
    val_fraction: 0.1
  
train_args:
    max_epochs: 1000
    seed: 42
    early_stop_patience: 10
    magnitude: 0.7

checkpoint:
    vertex_features: output_parameters/smallCNN_vertex_features.pt
    edge_features: output_parameters/smallCNN_edge_features.pt
    
optimization:
    clip_grad: True
    clip_grad_max_norm: 10.0
    optimizer_name: Adam
    optimizer_args:
        lr: 0.01
    scheduler_args:
        scheduler: WarmupLRScheduler
        warmup_steps: 1000
        scheduler_mode: min
        decay_rate: 0
        decay_steps: 0
        patience: None
        min_lr: None
